name: designs
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  provider: ^6.0.3
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets: 
    - assets/svgs/slide-1.svg
    - assets/svgs/slide-2.svg
    - assets/svgs/slide-3.svg
    - assets/svgs/slide-4.svg
    - assets/svgs/slide-5.svg
